---
title: "Detector de metales"
author: "Silvia 79"
date: "7/30/2021"
output:
  xaringan::moon_reader:
    self_contained: true
    lib_dir: libs
    seal: false
    #nature:
      #ratio: '16:9'

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval=T, message=FALSE, warning=FALSE)
```

background-color: black


<span style="color: white; font-size: 30px">**Detector de metales**</span>

<span style="color: white;">_Seudónimo:_  Silvia 79</span>

```{r lectura_datos_espaciales}
#Primero se leo los datos espaciales: un vectorial de puntos con dos campos, ID (un posible orden de la lectura) y lugar (el nombre de la ciudad o sitio). El relato asociado a cada punto tiene más de 254 caracteres, por lo que no puede guardarse en un campo del archivo vectorial.
library(sf)
library(dplyr)
detectormetales <- st_read("data/DetectorMetales.shp", quiet=TRUE) %>%
  arrange(id)
```

```{r lectura_relato}
#Ahora leo el relato (una lista con un ítem ordenada según el ID) y lo asigno a cada punto georreferenciado.
relato <- read.csv("data/relato.txt", header=FALSE)
relato$V2 <- NULL
relato$id <- c(1,2,3,4,5)
detectormetales<-left_join(detectormetales, relato)
```

```{r librerias_leaflet}
library(leaflet)
library(htmltools)
```

```{r mapabase_OSM}
#Por último genero el mapa, con sintaxis de Leaflet y un proveedor de mapa base de OpenStreetMap que simula una acuarela.
mapa_base <-leaflet(width="100%", height = "75%") %>% 
  addProviderTiles("Stamen.Watercolor", group="Acuarela", options = providerTileOptions(attribution = "Acuarela de fondo: Stamen Design Watercolor, CC BY 3.0. Datos OpenStreetMap, CC BY SA 2.0" )) %>%
  addProviderTiles("OpenStreetMap.Mapnik", group = "Mapa", options = providerTileOptions(attribution = "Mapa de fondo: © OpenStreetMap contributors, CC BY-SA 2.0" )) %>%
  addProviderTiles("Esri.WorldImagery", group = "Satelital", options = providerTileOptions(attribution = "Imágenes de fondo: © Esri; Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, y GIS User Community" )) %>%
  setView(-60,-34, zoom = 5) 
#mapa_base
```

```{r mapafinal}
#Cada punto corresponde a un marcador con una etiqueta con el relato. 

icons <- awesomeIcons(
  icon = 'ios-keypad',
  iconColor = 'white',
  library = 'ion',
  markerColor = c("tomato", "cadetblue", "blue", "green", "purple")
)

etiqueta <- popupOptions(
  maxWidth=500)

mapa_final <- mapa_base  %>%
  addAwesomeMarkers(data=detectormetales,
              popup=~detectormetales$V1,
              popupOptions=etiqueta,
              icon=icons) %>% 
  addLayersControl(baseGroups = c("Acuarela", "Satelital", "Mapa")) 


mapa_final

```

<span style="color: white; font-size: 12px; float: right">
[Versión accesible](https://github.com/nmorandeira/detectordemetales/blob/main/detectordemetales.md) para personas ciegas, con visión limitada u otras dificultades para interactuar con el mapa.
</span>


```{r index.html}

file.copy("detectordemetales.html", to="docs/")
file.rename("docs/detectordemetales.html", to="docs/index.html")
file.remove("docs/detectordemetales.html")
file.remove("detectordemetales.html")

```
